export default {
  logo: require('../assets/Logo.png'),
  On2: require('../assets/On2.png'),
  food: require('../assets/Food.png'),
  leaves: require('../assets/leaves.jpeg'),
  tree: require('../assets/images.jpeg'),
  logologin: require('../assets/diet.png'),
  Hehe: require('../assets/Hehe.png'),
  lo1: require('../assets/location1.jpg'),
  lo2: require('../assets/location2.jpg'),
  salat: require('../assets/foodImage/salat.jpg'),
  suon: require('../assets/foodImage/thumbcn-1200x676-13.jpg'),
  xoi: require('../assets/foodImage/XoiXoi.jpg'),
  cam: require('../assets/foodImage/fresh-orange-juice-jar-1748.jpg'),
};
